# Generated by Django 4.0.6 on 2022-08-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
                ('creation_date', models.DateField()),
                ('type_of_post', models.CharField(max_length=200)),
                ('creator', models.ManyToManyField(related_name='posts', to='posts.user')),
                ('likes_for_this_post', models.ManyToManyField(related_name='likes', to='posts.user')),
                ('shares_for_this_post', models.ManyToManyField(related_name='shares', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='posts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commented_date', models.DateField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.post')),
                ('user', models.ManyToManyField(related_name='comments', to='posts.user')),
            ],
        ),
    ]
