# Generated by Django 4.0.6 on 2022-07-21 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 21, 18, 5, 28, 371487)),
        ),
    ]
