# Generated by Django 4.0.6 on 2022-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='users', to='profile_manager.baseuser'),
        ),
    ]
