# Generated by Django 4.0.7 on 2022-08-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_mgmt.baseuser')),
                ('name', models.CharField(max_length=300)),
                ('phone_numbers', models.IntegerField()),
                ('head_of_organization', models.CharField(max_length=300)),
                ('research_institution', models.BooleanField(blank=True, default=False, null=True)),
                ('education_institution', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('user_mgmt.baseuser',),
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='role',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_mgmt.baseuser')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('interests', models.TextField(blank=True, max_length=200, null=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='teacher', to='user_mgmt.course')),
                ('institution', models.ManyToManyField(blank=True, null=True, related_name='teacher', to='user_mgmt.institution')),
            ],
            bases=('user_mgmt.baseuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_mgmt.baseuser')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('interests', models.TextField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('U', 'Unicorn'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='Unicorn', max_length=1)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='students', to='user_mgmt.course')),
                ('institution', models.ManyToManyField(blank=True, null=True, related_name='students', to='user_mgmt.institution')),
            ],
            bases=('user_mgmt.baseuser',),
        ),
        migrations.AddField(
            model_name='institution',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='user_mgmt.baseuser'),
        ),
        migrations.AddField(
            model_name='institution',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='user_mgmt.course'),
        ),
    ]
