# Generated by Django 4.0.7 on 2022-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_course_institution_remove_baseuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='user_mgmt.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ManyToManyField(related_name='students', to='user_mgmt.institution'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teacher', to='user_mgmt.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institution',
            field=models.ManyToManyField(related_name='teacher', to='user_mgmt.institution'),
        ),
    ]
