# Generated by Django 4.0.7 on 2022-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='connections',
            field=models.ManyToManyField(to='user_mgmt.baseuser'),
        ),
    ]
